### ISSUE TITLE
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

### ISSUE THREAD

**Issue by grayapply2009** [pepkit/geofetch#16]
My command: `python geofetch.py -i GSE86043`

```
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/guol03/.wget-hsts'. HSTS will be disabled.

SRP: SRP086702
Parsing SRA file to download SRR records
Traceback (most recent call last):
  File "geofetch.py", line 760, in <module>
    main(sys.argv[1:])
  File "geofetch.py", line 536, in main
    for line in input_file:
  File "/home/guol03/anaconda3/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/home/guol03/anaconda3/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

**Comment by nsheff** [comment]
That's a python 3 problem.
Try using `python2`:

````
python2 geofetch.py -i GSE86043
```

**Comment by nsheff** [comment]
Right now we haven't extensively tested geofetch with python 3, but we should...

**Comment by grayapply2009** [comment]
Thank you for your quick response, Nathan. I'm trying it now.

**Comment by vreuter** [comment]
Feel free to reopen @grayapply2009 if this happens with Python2 as well; regardless, this has spawned #18
