### ISSUE TITLE
NameError: name 'Sys' is not defined

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/geofetch#41]
```
You must provide a geo_folder to download processed data.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/geofetch", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/geofetch/geofetch.py", line 896, in main
    run_geofetch(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/geofetch/geofetch.py", line 591, in run_geofetch
    Sys.exit
NameError: name 'Sys' is not defined
```

**Comment by Khoroshevskyi** [comment]
Was fixed in the v0.8.0
