### ISSUE TITLE
Error giving sample list file

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#62]
Given  example_sample_list_2.tsv like this:

```
GSE27432	GSM678211	

```

I get this error:
```
geofetch -i example_sample_list_2.tsv 
Metadata folder: /home/nsheff/garage/geofetch/example_sample_list_2
Accession list file found: example_sample_list_2.tsv
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/geofetch", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/geofetch/geofetch.py", line 1591, in main
    Geofetcher(args).fetch_all()
  File "/home/nsheff/.local/lib/python3.8/site-packages/geofetch/geofetch.py", line 147, in fetch_all
    acc_GSE_list = parse_accessions(
  File "/home/nsheff/.local/lib/python3.8/site-packages/geofetch/utils.py", line 120, in parse_accessions
    if acc_GSE_list.has_key(gse):  # GSE already has a GSM; add the next one
AttributeError: 'dict' object has no attribute 'has_key'
```

**Comment by Khoroshevskyi** [comment]
This issue was fixed in v0.8.0, could you please check if you still have this error? @nsheff
