### ISSUE TITLE
KeyError: 'Experiment' with missing SRP#

### ISSUE THREAD

**Issue by nsheff** [pepkit/geofetch#8]
```
  Found sample GSM678211  Unable to get SRA accession (SRP#) from GEO GSE SOFT file. No raw data?
But the GSM has an SRX number; 
Instead of an SRP, using SRX identifier for this sample:  GSM678211
--2018-11-02 12:24:34--  http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=gsm&acc=GSM678211&form=text&view=full
Resolving www.ncbi.nlm.nih.gov (www.ncbi.nlm.nih.gov)... 130.14.29.110
Connecting to www.ncbi.nlm.nih.gov (www.ncbi.nlm.nih.gov)|130.14.29.110|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=gsm&acc=GSM678211&form=text&view=full [following]
--2018-11-02 12:24:34--  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=gsm&acc=GSM678211&form=text&view=full
Connecting to www.ncbi.nlm.nih.gov (www.ncbi.nlm.nih.gov)|130.14.29.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [geo/text]
Saving to: ‘/sfs/lustre/allocations/shefflab/data/sra_meta/GEO_rrbs_diverse/GSE27432_SRA.csv’

    [ <=>                                                                                      ] 3,319       --.-K/s   in 0s      

2018-11-02 12:24:35 (294 MB/s) - ‘/sfs/lustre/allocations/shefflab/data/sra_meta/GEO_rrbs_diverse/GSE27432_SRA.csv’ saved [3319]

SRP: GSM678211
Parsing SRA file to download SRR records
Traceback (most recent call last):
  File "/home/ns5bc/code//geofetch/geofetch/geofetch.py", line 750, in <module>
    main(sys.argv[1:])
  File "/home/ns5bc/code//geofetch/geofetch/geofetch.py", line 543, in main
    experiment = line["Experiment"]
KeyError: 'Experiment'
```

**Comment by nsheff** [comment]
I think this may arise from giving a GSM number instead of GSE number  to geofetch...

**Comment by Khoroshevskyi** [comment]
If you will give GSM number as input, it won't download it, as geofetch expecting GSE number. Additionally, in new version, while providing file with few experiment numbers, including one GSM number, then process won't stop, it will just inform you, that it's imposible to download GSM. 

I assume, that this issue can be closed now.
